### ISSUE TITLE
New model: 19167 The Application of “Ubiquitous Public Access--to--Geographic Information” for Air Quality Information

### ISSUE THREAD

**Issue by jetgeo** [ISO-TC211/HMMG#14]
_From @jetgeo on May 2, 2017 11:2_

The Application of “Ubiquitous Public Access--to--Geographic Information” for Air Quality Information

Note: This is not a standard, just a technical report. The UML is based on ISO19154 Ubiquitous Public Access - Reference Model. The model for 19167 should also be in the HM, probably under Informative. 

_Copied from original issue: ISO-TC211/HMMG_old#24_

**Comment by geonuri** [comment]
Hello, 
I sent an e-mail including UMLs in ISO19167 two days ago. Also, I tried to upload the those file using SVN. But I am not sure those files were uploaded correctly.

**Comment by jetgeo** [comment]
I need the EA files, not the exported diagrams. Can you either provide me with the EA project you have used, or export an XMI file from EA? I cannot see anything new uploaded in the Harmonized Model.
