### ISSUE TITLE
Naming conventions for models

### ISSUE THREAD

**Issue by jetgeo** [ISO-TC211/HMMG#19]
Suggestion:
Top level: 
* Package Name = "ISO19115 - Metadata"
* Package Alias = "Metadata"
* Tagged value "name" = "Metadata"
* Tagged value "number" = "19115"

Version level :
* Package Name = "ISO19115-2 Ed2"
* Package Alias = "Metadata - Extensions for acqusition and processing"
* Package Version = "2017"
* Tagged value "name" = "Metadata - Extensions for acqusition and processing"
* Tagged value "number" = "19115-2"
* Tagged value "version" = "2017"

Version level :
* Package Name = "ISO19115-2 Ed1"
* Package Alias = "Metadata - Extensions for imagery and gridded data"
* Package Version = "2009"
* Tagged value "name" = "Metadata - Extensions for imagery and gridded data"
* Tagged value "number" = "19115-2"
* Tagged value "version" = "2009"

**Comment by jetgeo** [comment]
Modified suggestion, test implementation on the 19111 package:

**Top level:**
Package Name = "ISO19111 Referencing by coordinates"
Package Alias = "Referencing by coordinates"
Tagged value "name" = "Referencing by coordinates"
Tagged value "number" = "19111"

Edition level :
Package Name = "ISO19111 Edition 2"
Package Alias = "Referencing by coordinates"
Package Version = "2017"
Tagged value "name" = "Referencing by coordinates"
Tagged value "number" = "19111"
Tagged value "version" = "2017"

Edition level :
Package Name = "ISO19111 Edition 1"
Package Alias = "Spatial referencing by coordinates"
Package Version = "2007"
Tagged value "name" = "Spatial referencing by coordinates"
Tagged value "number" = "19111"
Tagged value "version" = "2007"

Edition level :
Package Name = "ISO19111-2 Edition 1"
Package Alias = "Spatial referencing by coordinates - Extension for parametric value"
Package Version = "2009"
Tagged value "name" = "Spatial referencing by coordinates - Extension for parametric value"
Tagged value "number" = "19111-2"
Tagged value "version" = "2009"

**Comment by jetgeo** [comment]
I see one issue though: Because we are using the official ISO edition, we end up with some confusing package names:

ISO19103 get two “Edition 1” packages, because the first version was a technical specification. May be solved by adding “Technical Specification” to the package name. 

ISO19115 get several versions of both “Edition 1” and Edition 2”, because the original standard was just 19115, while the new version is split into 19115-1 and 19115-2. 

I am not sure if this is a problem, but at least it must be described in the article. The use of suffixes “Technical Specifiaction”, “Amendment” and “Corrigendum” must also be described.

**Comment by jetgeo** [comment]
I think we should have a space between ISO and the number, i.e. "ISO 19103 Conceptual schema language".

**Comment by DaveDanko** [comment]
now that we've reorganized and renamed the packages (ISO 191xx Edition 1 vs ISO 191xx:2014 the package dependency diagram is not consistent 
for example:
Now it looks like this: newway
![newway](https://user-images.githubusercontent.com/11442205/29191139-b5459ef6-7dea-11e7-8094-e6f008a2c8e0.PNG)
instead of looking like this: oldway
![oldway](https://user-images.githubusercontent.com/11442205/29191181-dd7fdb5c-7dea-11e7-8528-8eb870b5a4f1.PNG)
Will ISO accept this?

**Comment by jetgeo** [comment]
I can't see why they should not accept it. It is just a different way of referring to the same standard ("ISO 19115-1 Edition 1" instead of "ISO 19115-1:2014 Metadata fundamentals"). 
The 19157 package names has also been updated, so the figure now look like this:
![2017-08-11_0849](https://user-images.githubusercontent.com/7501876/29203554-0c0bb284-7e72-11e7-9631-94d4da52ffe2.png)
We will continue to update all package names based on this structure, and then diagrams will then be consistent.

**Comment by jetgeo** [comment]
Closed, further follow-up on wiki: https://github.com/ISO-TC211/HMMG/wiki/Package-naming-conventions
