### ISSUE TITLE
Hostname mismatch causes certificate validation failure message

### ISSUE THREAD

**Issue by joergklausen** [ISO-TC211/HMMG#27]
To whom it may concern:
SVN updating the https://inspire-twg.jrc.it:443 resource always returns above error message. It requires me to manually accept the certificate each time I want to use the ISO TC211 models in EA for our own Project. This is annoying. Can someone fix this, please?
Thanks a lot and kind regards
Jörg Klausen

**Comment by jetgeo** [comment]
Hi Jörg, and thanks for this input. Like the other error you have experienced, I believe this also is something local on your computer or in your network. I suggest that you report the error to Sparx, who will surely help you.

**Comment by jetgeo** [comment]
SVN server is now closed, we have moved to Sparx ProCloud.
