### ISSUE TITLE
SVN server certificate expired

### ISSUE THREAD

**Issue by cportele** [ISO-TC211/HMMG#28]
@jetgeo 

The server certificate of the SVN server expired yesterday morning, which creates issues for EA connections to the SVN.

```
Error validating server certificate for 'https://inspire-twg.jrc.ec.europa.eu:443':
 - The certificate is not issued by a trusted authority. Use the
   fingerprint to validate the certificate manually!
 - The certificate has expired.
Certificate information:
 - Hostname: inspire-twg.jrc.ec.europa.eu
 - Valid: from Mar 23 09:17:38 2009 GMT until Mar 21 09:17:38 2019 GMT
 - Issuer: inspire-twg.jrc.ec.europa.eu, SDI, JRC, Ispra, Varese, IT(inspire-info@jrc.cec.eu.int)
 - Fingerprint: 4E:D4:DD:63:95:EE:FF:6A:12:F4:18:26:0E:3D:6E:7F:8D:0F:6D:21
(R)eject, accept (t)emporarily or accept (p)ermanently?
```

**Comment by jetgeo** [comment]
I just noticed this too. I have asked JRC about it.

**Comment by jetgeo** [comment]
JRC is working to resolve this issue. 
In the meantime, it is possible, by doing an update on the repository outside EA (e.g. with TortoiseSVN), to permanently accept the expired certificate.

**Comment by michellutz** [comment]
We have put the svn server behind a reverse proxy, which should solve the certificate issue.

Please let us know if you keep having issues.

**Comment by jetgeo** [comment]
Great @michellutz. Closing this issue.
