### ISSUE TITLE
Error logging in to Harmonised Model on Sparx Cloud

### ISSUE THREAD

**Issue by PeterParslow** [ISO-TC211/HMMG#30]
Hi,
the description gives the impression that anyone can view the HTML model on the Sparx Cloud. However, choosing the "read-only" option leads to the error "The specified login details were not valid for the current model!"

Unsurprisingly, this is independent of whether I choose mobile, tablet, or desktop.

As expected, choosing "full" requests log in details.

**Comment by jetgeo** [comment]
I know. Sparx is working on the issue. It worked well in the beginning, but I am afraid I did something wrong with the read-only user 👎 .

**Comment by jetgeo** [comment]
Works now.
