### ISSUE TITLE
Downloadable EA project out of sync with the WebEA project

### ISSUE THREAD

**Issue by tobiasspears** [ISO-TC211/HMMG#33]
I was reviewing the ISO 19115-3:2016 Amendment 2 document that is out for ballot and noticed that Figure 12 in the downloadable EA project is out of sync from the amendment document and WebEA project.

I was referring to commit b1c9a5faf7781fb32be69d0f07196c6361898eb2 from earlier today.

I was wondering if the downloadable EA project could be refreshed from WebEA sometime soon, or if a mechanism could be put in place to allow read only access to the WebEA project on port 80 (the custom port is blocked at my location).

Thanks
Tobias

**Comment by jetgeo** [comment]
Thank you for noticing this. I have uploaded a new project with the correct version of ISO 19115-1 Ed 1 Amd 2 now.

**Comment by tobiasspears** [comment]
Thanks! I've noticed typos with the web site and within the EA project - nothing major, just cleanup. Do you have a preference for how to submit these (e.g. just occasionally submit in batches?).

Regards
Tobias

**Comment by jetgeo** [comment]
I'm happy to receive any input concerning the UML models and the text on this site. You can submit them as issues here. If there are many of them, please combine several comments as one issue.

**Comment by tobiasspears** [comment]
Sounds good - are you involved in the XMG and or OMG GitHub sites as well?

**Comment by jetgeo** [comment]
I am involved, but not responsible. Feel free to do the same job there :). 
@BrodeurJS is responsible for the GOM site, and @ejbleys is responsible for the XML sites.
