### ISSUE TITLE
Spellcheck corrections suggested for the HMMG Wiki

### ISSUE THREAD

**Issue by tobiasspears** [ISO-TC211/HMMG#34]
Good evening,
I cloned the Wiki for the HMMG project and ran a batch spellcheck to look for any typographic issues.

I have attached the report as an Excel workbook and prefiltered the main false positives:
I ran the same checks against the ISO-UML-BP project wiki as well and will submit an issue to that project once I have completed some preconditioning to filter out false positives.

[ISO_HM_Wiki_Spellcheck.xlsx](https://github.com/ISO-TC211/HMMG/files/4315595/ISO_HM_Wiki_Spellcheck.xlsx)

I reviewed the EA internal spellcheck facility and although it seems to work well, I did not see a batch/reporting option which is not overly helpful. I plan to write some custom mining/spellchecking against the XMI output for the full HM as I seeing spelling errors showing up in constraints and not just in notes and other free text properties. Once completed I will submit these as well.

Tobias

**Comment by jetgeo** [comment]
Thank you, I appreciate your input. I will correct the typos as soon as possible.

**Comment by tobiasspears** [comment]
No problem - UML- BP has been submitted. Now off to the HM EA project :)

**Comment by jetgeo** [comment]
I have invited you in as a member of the HMMG team on GitHub now. You may then edit and fix these typos yourself :).

**Comment by sptws001** [comment]
Potential typos were reviewed and updates applied as per the attachment. A small number of typos were also noted in Prefixes.md and corrected.

[ISO_HM_Wiki_Spellcheck.xlsx](https://github.com/ISO-TC211/HMMG/files/4376913/ISO_HM_Wiki_Spellcheck.xlsx)
