### ISSUE TITLE
Boolen datatype in ISO 19107

### ISSUE THREAD

**Issue by rggibb** [ISO-TC211/HMMG#35]
Geometry interface has a pair of 'equal' operations with return type Boolen, which should probably be Boolean. Boolen isn't mentioned in the N4883 19107 FDIS text, other than in Fig 10 which is an image from the HM.

**Comment by jetgeo** [comment]
Can be fixed in the HM, but need new figure in ISO 19107 as well. Added  to StandardsTracker as https://github.com/ISO-TC211/StandardsTracker/issues/393.

**Comment by jetgeo** [comment]
Ref. https://github.com/ISO-TC211/StandardsTracker/issues/393
