### ISSUE TITLE
Oppisite() operation for interface Orientable in ISO 19107

### ISSUE THREAD

**Issue by rggibb** [ISO-TC211/HMMG#36]
Text in N4883 19107 FDIS only mentions 'oppisite' in Fig 13 & Fig 16 both generated from the HM, where the associated text uses the words 'opposite' and 'reverse' in general discussion, and in 6.4.15.3 refers to the operation reverse(), but not opposite() or oppisite(). Thus possibly implying that the opperation in the HM should be reverse() and not oppisite(), or possibly opposite() if both are 'wrong'?

**Comment by jetgeo** [comment]
Must be fixed formally. Added to StandardsTracker as https://github.com/ISO-TC211/StandardsTracker/issues/394
