### ISSUE TITLE
GeometricCoordinateSystem attribute & operation spelling errors in ISO 19107

### ISSUE THREAD

**Issue by rggibb** [ISO-TC211/HMMG#37]
attribute 'spatailDimension' should be 'spatialDimension', cf 6.2.8.3 in 19107 Ed 2 text
operation 'foeLocate', should be 'geoLocate', cf 6.2.8.12 in 19107 Ed 2 text
operation 'bearting', should be 'bearing', cf cf 6.2.8.13 in 19107 Ed 2 text
all three erros have propagated to Fig 5 - Reference system and CRS in 19107 Ed 2

**Comment by jetgeo** [comment]
Must be fixed formally. Added to StandardsTracker as https://github.com/ISO-TC211/StandardsTracker/issues/395
