### ISSUE TITLE
Updated XMI 1.1 export for 19115 (full package) with spelling corrections

### ISSUE THREAD

**Issue by sptws001** [ISO-TC211/HMMG#39]
Good morning,
Attached is an updated version of the full conceptual model for ISO 19115 for integration into the HM. It was exported and updated from commit c2529fb7ea237f9b0c8bc74fae4f98a9a1f539f4 and XMI 1.1 format. It contains ~10 spelling corrections.

Thanks

Tobias

[Conceptual-ISO 19115_c2529fb7ea237f9b0c8bc74fae4f98a9a1f539f4_XMI_1_1_CLEAN.zip](https://github.com/ISO-TC211/HMMG/files/4398774/Conceptual-ISO.19115_c2529fb7ea237f9b0c8bc74fae4f98a9a1f539f4_XMI_1_1_CLEAN.zip)

**Comment by sptws001** [comment]
The list of elements and associated corrections included in the update XMI package are included below.

[changelog.txt](https://github.com/ISO-TC211/HMMG/files/4420794/changelog.txt)

**Comment by jetgeo** [comment]
Have you checked if these typos are in the document as well? If so, they should be handled in a revision/corrigendum of the standard. If they are correct in the document, then we can change them in the HM. 
Adding @PeterParslow and @RogerLott for information.
