### ISSUE TITLE
More detailed RAS

### ISSUE THREAD

**Issue by jetgeo** [ISO-TC211/HMMG#45]
RAS is now available at the main standard level. We need to have RAS for individual parts and editions.

**Comment by heidivanparys** [comment]
If I may submit a request for an order of priority in creating more RAS's: seem from a data modelling perspective, it would be great if we could have RAS's for

- ISO 19103:2015
- ISO 19107:2003 (yes, we're stilling using that version, probably quite some organisations do so)
- ISO 19108:2006

**Comment by jetgeo** [comment]
All individual standard editions are now published as individual RAS's, ordered in one storage per main standard.
