### ISSUE TITLE
19139 Packages in Drafts

### ISSUE THREAD

**Issue by jetgeo** [ISO-TC211/HMMG#5]
There are two ISO19139 Packages in Drafts:

- ISO 19139 NWIP Metadata - XML Implementation (last modified by Dave Danko 2012-09-07)

- ISO 19139-2, XML Implementation of ISO 19115-2 (last modified by Nicolas Lesage 2012-07-26)

I believe both of these packages can be removed, they have been superseeded by ISO 19115-2 in the implementation model. 

Correct?

**Comment by DaveDanko** [comment]
Shouldn't there be a ISO 19139-2:2012 in 19139 All?
or put the 19139-2 package in the Implementation area? (wherever that is)

the official title is ISO/TS 19139-1:2012 Metadata - XML Schema implementation - Part 2 - Extensions for Imagery and gridded data http://www.iso.org/iso/home/store/catalogue_tc/catalogue_detail.htm?csnumber=57104

**Comment by jetgeo** [comment]
Ahh, I see. "ISO 19139-2, XML Implementation of ISO 19115-2" is the XML Implementation of the old 19115-2, but not the one we incorporated in 19115-3. 

I'll move this package to the "ISO 19319 All" package for now, and maybe come back to whether or not it shall be moved to de Implementation Area, ref https://github.com/ISO-TC211/HMMG/issues/3

The package "ISO 19139 NWIP Metadata - XML Implementation" will be moved to a separate area for flotsam.

**Comment by jetgeo** [comment]
Done, new structure:
![image](https://cloud.githubusercontent.com/assets/7501876/12976215/ba1b6e6e-d0c2-11e5-8212-623a746e552d.png)
