### ISSUE TITLE
Missing model: 19166 BIM to GIS conceptual mapping (B2GM)

### ISSUE THREAD

**Issue by jetgeo** [ISO-TC211/HMMG#5]
_From @jetgeo on November 27, 2017 1:10_

_Copied from original issue: ISO-TC211/HMMG_old#34_

**Comment by mac999** [comment]
Thanks for making this repository. I'm participating in this project. I'm wondering who manage this repository. If there is any issue related to B2GM, let me know about it.

**Comment by jetgeo** [comment]
I am managing this repository on behalf of the HMMG in ISO/TC211. This issue is concerning the fact that the UML models from the 19166 B2GM project is missing in the Harmonized Model (HM). All UML models from ISO/TC211 standards shall be in the HM, which we maintain in Enterprise Architect. Please contact me directly, and we can discuss how to move forward with moving the 19166 UML models into the HM. 

Best regards, 
Knut Jetlund

**Comment by mac999** [comment]
Do you know UML file format which  ISO TC211 like it?
When I design class diagram, I use .StarUML opensource tool which can save
.uml file format.


+ 강태욱(Tae Wook, Kang) 드림
  Ph.D, Senior researcher, KICT <http://www.kict.re.kr/eng/>
  https://sites.google.com/site/bimprinciple/
  http://daddynkidsmakers.blogspot.kr/
  (82) 010-3008-5143

2018-03-12 22:59 GMT+09:00 Knut Jetlund <notifications@github.com>:

**Comment by jetgeo** [comment]
XMI is the prefererred format. StarUML seems to have an extention for XMI Import/Export. But you should rather use Enterprise Architect and work directly in the HM, as described in the Wiki: https://github.com/ISO-TC211/HMMG/wiki.

**Comment by mac999** [comment]
It's ok. I try to find how to export XMI using the tool or buy Enterprise
Architect.
Thanks.


+ 강태욱(Tae Wook, Kang) 드림
  Ph.D, Senior researcher, KICT <http://www.kict.re.kr/eng/>
  https://sites.google.com/site/bimprinciple/
  http://daddynkidsmakers.blogspot.kr/
  (82) 010-3008-5143

2018-03-12 23:19 GMT+09:00 Knut Jetlund <notifications@github.com>:

**Comment by mac999** [comment]
I exported XMI file from the B2GM ISO 19166 UML file. I'll send you the XMI and UML files by using email.

**Comment by mac999** [comment]
I attached the XMI and UML files related to ISO 19166 (B2GM).


+ 강태욱(Tae Wook, Kang) 드림
  Ph.D, Senior researcher, KICT <http://www.kict.re.kr/eng/>
  https://sites.google.com/site/bimprinciple/
  http://daddynkidsmakers.blogspot.kr/
  (82) 010-3008-5143

2018-03-13 8:33 GMT+09:00 Taewook Kang <laputa99999@gmail.com>:

**Comment by jetgeo** [comment]
Hi, seems like the file didn't get through. Can you send it to me directly on knut.jetlund@vegvesen.no?

**Comment by mac999** [comment]
I attached the XMI and UML files related to ISO 19166 (B2GM). In addition,
I used StarUML for exporting it.



+ 강태욱(Tae Wook, Kang) 드림
  Ph.D, Senior researcher, KICT <http://www.kict.re.kr/eng/>
  https://sites.google.com/site/bimprinciple/
  http://daddynkidsmakers.blogspot.kr/
  (82) 010-3008-5143

2018-03-22 20:07 GMT+09:00 Knut Jetlund <notifications@github.com>:

**Comment by jetgeo** [comment]
Please send the files directly to my email knut.jetlund@vegvesen.no from your email. Replying on a GitHub notification does not include the attachment.

**Comment by mac999** [comment]
I attached the files with UML made by StarUML.

+ 강태욱(Tae Wook, Kang) 드림
  Ph.D, Senior researcher, KICT <http://www.kict.re.kr/eng/>
  https://sites.google.com/site/bimprinciple/
  http://daddynkidsmakers.blogspot.kr/
  (82) 010-3008-5143

2018-03-22 21:46 GMT+09:00 Knut Jetlund <notifications@github.com>:
