### ISSUE TITLE
"Maintenance Group" instead of "Management Group"

### ISSUE THREAD

**Issue by ronaldtse** [ISO-TC211/HMMG#52]
<img width="872" alt="Screenshot 2022-06-23 at 3 16 05 PM" src="https://user-images.githubusercontent.com/11865/175228425-b2a41383-4c3f-4423-99f1-9657df1ee97c.png">

Just found this during the ISO 19115-3 editing meeting with @ejbleys .

**Comment by jetgeo** [comment]
Fixed. Thanks @ronaldtse :)

**Comment by ronaldtse** [comment]
Thanks @jetgeo ! Welcome back.
