### ISSUE TITLE
Encoding issue with WebEA

### ISSUE THREAD

**Issue by heidivanparys** [ISO-TC211/HMMG#57]
I noticed there is an encoding issue with the model available on [http://iso.sparxcloud.com](http://iso.sparxcloud.com/index.php).

![image](https://github.com/ISO-TC211/HMMG/assets/11427611/384e7893-9a2b-4a7f-aba8-76917d285d90)

vs

![image](https://github.com/ISO-TC211/HMMG/assets/11427611/70eef40d-9006-4dab-a2c4-4af300b51efa)

Is that something the HMMG can fix, or does it have to be reported to Sparx?

**Comment by chris-little** [comment]
It looks as if Sparx cannot handle a Unicode `Em Dash` (`—`).
`Em Dash` in UTF-8 is `0xE2 0x80 0x94` in hexadecimal, which Sparx is treating as Windows Code Page 1252 giving `â € "`

**Comment by heidivanparys** [comment]
It seems that this has been solved in the meantime:

![image](https://github.com/ISO-TC211/HMMG/assets/11427611/67d615c0-497f-4a97-a6fe-3e6c7e36bd9a)
