### ISSUE TITLE
Add instructions on how to use ISO19103 MDG in EA

### ISSUE THREAD

**Issue by ronaldtse** [ISO-TC211/HMMG#58]
As a Mac user I'm using Enterprise Architect 16.1 through CrossOver.

Here are the steps I used to (finally) install the MDG XML.

1. Go to the "Specialize" ribbon bar

<img width="977" alt="Screenshot 2024-06-26 at 3 17 55 PM" src="https://github.com/ISO-TC211/HMMG/assets/11865/d77da051-50a0-4a2f-b618-1e9d2c871456">

2. Click on "Manage Technology"
<img width="977" alt="Screenshot 2024-06-26 at 3 20 15 PM" src="https://github.com/ISO-TC211/HMMG/assets/11865/c498d7b4-348e-44cd-8d98-6a7e0e42b3be">

3. Enter the "Manage Technology" screen

<img width="977" alt="Screenshot 2024-06-26 at 3 18 06 PM" src="https://github.com/ISO-TC211/HMMG/assets/11865/31c0f31f-e35f-44fa-96f5-2d50a82d31df">

4. Click on "Add" and select "Add URL"

<img width="977" alt="Screenshot 2024-06-26 at 3 18 34 PM" src="https://github.com/ISO-TC211/HMMG/assets/11865/037bfacc-2276-49e3-a459-22681f56c5b9">

5. Enter this path that points to the HMMG's location:
* https://raw.githubusercontent.com/ISO-TC211/HMMG/master/EA/ISO19103MDG%20v1.0.0-beta.xml

<img width="977" alt="Screenshot 2024-06-26 at 3 18 41 PM" src="https://github.com/ISO-TC211/HMMG/assets/11865/06d71ec8-c468-4caf-a8e3-41f5214ace41">

6. Then you see the "ISO 19103" profile installed in EA.

<img width="977" alt="Screenshot 2024-06-26 at 3 18 51 PM" src="https://github.com/ISO-TC211/HMMG/assets/11865/a65924af-6f15-4f7d-afe1-9c14abb83a62">

7. Try out loading the Harmonized Model!

**Comment by ronaldtse** [comment]
@jetgeo maybe we can copy/paste these instructions to the Wiki so others can find reference!

**Comment by heidivanparys** [comment]
I would actually recommend linking to the EA user guide, more specifically https://sparxsystems.com/eahelp/importmdgtechnologies.html in this case. This will save us for having to update documentation and/or for having outdated documentation on our website.

Tip: for any page in the documentation: take the last part, the file name (e.g. `importmdgtechnologies.html`), and put `https://sparxsystems.com/eahelp/` in front of that. When resolving the link you then obtain, you will be redirected to that page in the user guide for the latest EA guide. In this case https://sparxsystems.com/enterprise_architect_user_guide/16.1/modeling_frameworks/importmdgtechnologies.html.

**Comment by jetgeo** [comment]
Fixed as suggested by @heidivanparys - see https://github.com/ISO-TC211/HMMG/tree/master/EA#readme

**Comment by ronaldtse** [comment]
It took me a long time to understand the Sparx System help page 🤣 

There is also no where that tells the user how to add the MDG, as a path or as a URL.

**Comment by heidivanparys** [comment]
I actually wouldn't recommend users to add the MDG as URL. It means you won't have access to it when you work offline. This is an advanced option, described at https://sparxsystems.com/eahelp/access_remote_mdg_technologies.html.

**Comment by ronaldtse** [comment]
@heidivanparys On a Mac, Enterprise Architect cannot load the MDG XML when I use the "Add Path" option. Of course it could work perfectly on Windows.
