### ISSUE TITLE
Two versions of ISO19130 in the HM

### ISSUE THREAD

**Issue by jetgeo** [ISO-TC211/HMMG#8]
Which one is correct?

**Comment by jetgeo** [comment]
19115-2 is referencing the package ISO 19130:2010 Sensor Data.

**Comment by BrodeurJS** [comment]
GOM has asked WG6 to clarify this issue about a year ago. The ontology derivation will not be processed until this is cleaned up!

Jean,

Jean Brodeur
Envoyé de mon iPhone

**Comment by jetgeo** [comment]
Done - checked with WG 6 convenor. Only one version now.
